name: Bug report
description: Report an issue or bug with this library
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: non_api
    attributes:
      label: Confirm this is an issue with the MCP Server and not an underlying Trustwise API / SDK
      description: Issues with the underlying Trustwise API should be reported on our [Support Email](mailto:support@trustwise.ai), or the issue with Trustwise SDK should be reported on the [Trustwise SDK GitHub Repository](https://github.com/trustwiseai/trustwise)
      options:
        - label: This is an issue with the MCP Server
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and any additional context.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Fetch a '...'
        2. Update the '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: Python
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS
    validations:
      required: true
  - type: input
    id: client-app
    attributes:
      label: Client Application
      placeholder: Claude Desktop 0.9.3
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Trustwise MCP Server version
      placeholder: ghcr.io/trustwiseai/trustwise-mcp-server:v1.0.0
    validations:
      required: true